name: Rust Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04]
        rust: [stable, beta, nightly]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and test
      run: |
        cargo build --verbose
        cargo test --verbose

    - name: Check code formatting
      run: cargo fmt -- --check

    - name: Check for clippy warnings
      run: cargo clippy --all-targets --all-features -- -D warnings
